/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["content.index"];
        put?: never;
        post: operations["content.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{contentItem}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["content.assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/assignments/{contentAssignment}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["content.updateProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{contentItem}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["content.progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["evaluation.index"];
        put?: never;
        post: operations["evaluation.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["evaluation.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation}/submit-self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["evaluation.submitSelf"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation}/submit-manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["evaluation.submitManager"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["feedback.received"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["feedback.sent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["feedback.team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["feedback.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{pointwiseFeedback}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["feedback.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["kpi.index"];
        put?: never;
        post: operations["kpi.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kpis/{kpi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["kpi.update"];
        post?: never;
        delete: operations["kpi.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kpi-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["kpi.indexResults"];
        put?: never;
        post: operations["kpi.upsertResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/one-on-ones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oneOnOne.index"];
        put?: never;
        post: operations["oneOnOne.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/one-on-ones/{oneOnOne}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oneOnOne.show"];
        put: operations["oneOnOne.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/one-on-ones/{oneOnOne}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["oneOnOne.storeTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/one-on-ones/{oneOnOne}/topics/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["oneOnOne.updateTopic"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/one-on-ones/{oneOnOne}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["oneOnOne.storeNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pdi.index"];
        put?: never;
        post: operations["pdi.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdis/{pdi}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pdi.tasks"];
        put?: never;
        post: operations["pdi.storeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdis/{pdi}/tasks/{task}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["pdi.submitTask"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdis/{pdi}/tasks/{task}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["pdi.reviewTask"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile.show"];
        put: operations["profile.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile.team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sector.index"];
        put?: never;
        post: operations["sector.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sectors/{sector}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["sector.update"];
        post?: never;
        delete: operations["sector.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smart-forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["smartForm.index"];
        put?: never;
        post: operations["smartForm.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smart-forms/{smartForm}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["smartForm.show"];
        put: operations["smartForm.update"];
        post?: never;
        delete: operations["smartForm.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smart-forms/{smartForm}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["smartForm.indexResponses"];
        put?: never;
        post: operations["smartForm.storeResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smart-forms/{smartForm}/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["smartForm.aggregate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user.index"];
        put?: never;
        post: operations["user.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["user.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["user.deactivate"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppRole
         * @enum {string}
         */
        AppRole: "admin" | "gestor" | "colaborador" | "analista";
        /** AssignContentRequest */
        AssignContentRequest: {
            user_ids: string[];
        };
        /** AuthUserResource */
        AuthUserResource: {
            id: string;
            name: string;
            email: string;
            profile?: components["schemas"]["ProfileResource"];
            roles?: string[];
        };
        /** ContentAssignmentResource */
        ContentAssignmentResource: {
            id: string;
            item_id: string;
            user_id: string;
            status: string;
            seen_at: string;
            completed_at: string;
            assigned_at: string;
            item?: components["schemas"]["ContentItemResource"];
            user?: components["schemas"]["UserResource"];
        };
        /** ContentItemResource */
        ContentItemResource: {
            id: string;
            created_by: string;
            type: string;
            title: string;
            description: string;
            link_url: string;
            file_url: string;
            due_date: string;
            created_at: string;
            assignments?: components["schemas"]["ContentAssignmentResource"][];
        };
        /**
         * ContentStatus
         * @enum {string}
         */
        ContentStatus: "not_seen" | "seen" | "in_progress" | "completed";
        /**
         * ContentType
         * @enum {string}
         */
        ContentType: "training" | "reading" | "process";
        /** CreateContentItemRequest */
        CreateContentItemRequest: {
            type: components["schemas"]["ContentType"];
            title: string;
            description?: string | null;
            /** Format: uri */
            link_url?: string | null;
            /** Format: uri */
            file_url?: string | null;
            /** Format: date-time */
            due_date?: string | null;
        };
        /** CreateEvaluationRequest */
        CreateEvaluationRequest: {
            /** Format: uuid */
            assigned_to: string;
            type: components["schemas"]["EvaluationType"];
            flow_type?: components["schemas"]["EvaluationFlowType"];
            month: number;
            year: number;
            /** Format: uuid */
            smart_form_id?: string | null;
        };
        /** CreateFeedbackRequest */
        CreateFeedbackRequest: {
            /** Format: uuid */
            to_user_id: string;
            type: components["schemas"]["FeedbackType"];
            content: string;
            visibility?: components["schemas"]["FeedbackVisibility"];
        };
        /** CreateNoteRequest */
        CreateNoteRequest: {
            content: string;
            /** @enum {string} */
            type?: "decision" | "action" | "observation";
        };
        /** CreateOneOnOneRequest */
        CreateOneOnOneRequest: {
            /** Format: uuid */
            report_id: string;
            /** Format: date-time */
            scheduled_at: string;
            /** @enum {string|null} */
            recurrence_rule?: "weekly" | "biweekly" | "monthly" | null;
            notes?: string | null;
        };
        /** CreatePdiRequest */
        CreatePdiRequest: {
            title: string;
            description?: string | null;
            /** Format: date-time */
            start_date?: string | null;
            /** Format: date-time */
            end_date?: string | null;
        };
        /** CreatePdiTaskRequest */
        CreatePdiTaskRequest: {
            title: string;
            description?: string | null;
            /** Format: uri */
            link?: string | null;
            /** Format: date-time */
            due_date?: string | null;
        };
        /** CreateSmartFormRequest */
        CreateSmartFormRequest: {
            name: string;
            slug: string;
            status?: components["schemas"]["SmartFormStatus"];
            category: components["schemas"]["SmartFormCategory"];
            /** Format: uuid */
            sector_id?: string | null;
            config: {
                steps: string[];
            };
        };
        /** CreateTopicRequest */
        CreateTopicRequest: {
            content: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            role?: components["schemas"]["AppRole"];
            /** Format: uuid */
            sector_id?: string | null;
            /** Format: uuid */
            manager_id?: string | null;
        };
        /**
         * EvaluationFlowType
         * @enum {string}
         */
        EvaluationFlowType: "sequential" | "blind";
        /** EvaluationResource */
        EvaluationResource: {
            id: string;
            status: string;
            type: string;
            flow_type: string;
            month: number;
            year: number;
            smart_form_id: string;
            created_at: string;
            assignee?: components["schemas"]["UserResource"];
            creator?: components["schemas"]["UserResource"];
            responses?: components["schemas"]["EvaluationResponseResource"][];
        };
        /** EvaluationResponseResource */
        EvaluationResponseResource: {
            id: string;
            self_score: number | null;
            manager_score: number | null;
            final_score: number | null;
        };
        /**
         * EvaluationType
         * @enum {string}
         */
        EvaluationType: "cultural" | "performance" | "kpi";
        /** FeedbackResource */
        FeedbackResource: {
            id: string;
            type: string;
            content: string;
            visibility: string;
            created_at: string;
            to_user_id: string;
            from_user_id: string | null;
            from_user?: components["schemas"]["UserResource"] | null;
            to_user?: components["schemas"]["UserResource"];
        };
        /**
         * FeedbackType
         * @enum {string}
         */
        FeedbackType: "kudos" | "adjustment" | "observation";
        /**
         * FeedbackVisibility
         * @enum {string}
         */
        FeedbackVisibility: "private" | "with_manager";
        /** KpiResource */
        KpiResource: {
            id: string;
            name: string;
            description: string;
            target_value: number;
            unit: string;
            sector_ids?: string[];
            sectors?: components["schemas"]["SectorResource"][];
        };
        /** KpiResultResource */
        KpiResultResource: {
            id: string;
            kpi_id: string;
            user_id: string;
            score: number;
            month: number;
            year: number;
            created_at: string;
            kpi?: components["schemas"]["KpiResource"];
        };
        /**
         * KpiUnit
         * @enum {string}
         */
        KpiUnit: "percentual" | "numero" | "moeda" | "tempo" | "custom";
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** OneOnOneNoteResource */
        OneOnOneNoteResource: {
            id: string;
            content: string;
            type: string;
            author_user_id: string;
            created_at: string;
        };
        /** OneOnOneResource */
        OneOnOneResource: {
            id: string;
            manager_id: string;
            report_id: string;
            scheduled_at: string;
            recurrence_rule: string;
            status: string;
            notes: string;
            created_at: string;
            manager?: components["schemas"]["UserResource"];
            report?: components["schemas"]["UserResource"];
            topics?: components["schemas"]["OneOnOneTopicResource"][];
            notes_list?: components["schemas"]["OneOnOneNoteResource"][];
        };
        /** OneOnOneTopicResource */
        OneOnOneTopicResource: {
            id: string;
            content: string;
            addressed: boolean;
            author_user_id: string;
            created_at: string;
        };
        /** PdiResource */
        PdiResource: {
            id: string;
            user_id: string;
            title: string;
            description: string;
            end_date: string;
            created_at: string;
            tasks?: components["schemas"]["PdiTaskResource"][];
            user?: components["schemas"]["UserResource"];
        };
        /** PdiTaskResource */
        PdiTaskResource: {
            id: string;
            pdi_id: string;
            title: string;
            description: string;
            link: string;
            completed: boolean;
            due_date: string;
            status: string;
            reviewer_id: string;
            review_notes: string;
            reviewed_at: string;
            created_at: string;
        };
        /** ProfileResource */
        ProfileResource: {
            id: string;
            user_id: string;
            email: string;
            full_name: string;
            avatar_url: string;
            sector_id: string;
            manager_id: string;
            preferred_language: string;
            active: boolean;
            sector?: components["schemas"]["SectorResource"];
        };
        /** ReviewTaskRequest */
        ReviewTaskRequest: {
            /** @enum {string} */
            status: "approved" | "rejected";
            review_notes?: string | null;
        };
        /** SectorResource */
        SectorResource: {
            id: string;
            name: string;
            description: string;
        };
        /**
         * SmartFormCategory
         * @enum {string}
         */
        SmartFormCategory: "evaluation" | "onboarding" | "survey" | "feedback" | "custom";
        /** SmartFormResource */
        SmartFormResource: {
            id: string;
            name: string;
            slug: string;
            config: string;
            status: string;
            category: string;
            sector_id: string;
            created_at: string;
        };
        /** SmartFormResponseResource */
        SmartFormResponseResource: {
            id: string;
            form_id: string;
            form_slug: string;
            user_id: string;
            assigned_to: string;
            responses: string;
            status: string;
            completed_at: string;
            created_at: string;
            user?: components["schemas"]["UserResource"];
        };
        /**
         * SmartFormStatus
         * @enum {string}
         */
        SmartFormStatus: "draft" | "active" | "archived";
        /** StoreKpiRequest */
        StoreKpiRequest: {
            name: string;
            description?: string | null;
            target_value: number;
            unit?: components["schemas"]["KpiUnit"];
            sector_ids?: string[] | null;
        };
        /** SubmitFormResponseRequest */
        SubmitFormResponseRequest: {
            responses: string[];
            /** Format: uuid */
            assigned_to?: string | null;
        };
        /** SubmitResponseRequest */
        SubmitResponseRequest: {
            scores: {
                score: number;
            }[];
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            full_name?: string;
            /** Format: uri */
            avatar_url?: string | null;
            /** Format: uuid */
            sector_id?: string | null;
            /** Format: uuid */
            manager_id?: string | null;
            /** @enum {string} */
            preferred_language?: "pt" | "es";
        };
        /** UpdateProgressRequest */
        UpdateProgressRequest: {
            status: components["schemas"]["ContentStatus"];
        };
        /** UpdateSmartFormRequest */
        UpdateSmartFormRequest: {
            name?: string;
            slug?: string;
            status?: components["schemas"]["SmartFormStatus"];
            category?: components["schemas"]["SmartFormCategory"];
            /** Format: uuid */
            sector_id?: string | null;
            config?: {
                steps?: string[];
            };
        };
        /** UpsertKpiResultRequest */
        UpsertKpiResultRequest: {
            /** Format: uuid */
            kpi_id: string;
            /** Format: uuid */
            user_id?: string;
            score: number;
            month: number;
            year: number;
        };
        /** UserResource */
        UserResource: {
            id: string;
            name: string;
            email: string;
            profile?: components["schemas"]["ProfileResource"];
            roles?: string[];
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: unknown;
                        user: components["schemas"]["AuthUserResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AuthUserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthUserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logout realizado com sucesso.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "content.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Array of `ContentItemResource`
             *
             *     Array of `ContentAssignmentResource`
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContentItemResource"][];
                    } | {
                        data: components["schemas"]["ContentAssignmentResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "content.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContentItemRequest"];
            };
        };
        responses: {
            /** @description `ContentItemResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContentItemResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "content.assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content item ID */
                contentItem: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignContentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Conteúdo atribuído.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "content.updateProgress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content assignment ID */
                contentAssignment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProgressRequest"];
            };
        };
        responses: {
            /** @description `ContentAssignmentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContentAssignmentResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "content.progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content item ID */
                contentItem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        not_seen: number;
                        in_progress: number;
                        completed: number;
                        completion_rate: number;
                    } | {
                        total: number;
                        completed: number;
                        completion_rate: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "evaluation.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `EvaluationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EvaluationResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "evaluation.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRequest"];
            };
        };
        responses: {
            /** @description `EvaluationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EvaluationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "evaluation.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The evaluation ID */
                evaluation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `EvaluationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EvaluationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "evaluation.submitSelf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The evaluation ID */
                evaluation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResponseRequest"];
            };
        };
        responses: {
            /** @description `EvaluationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EvaluationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "evaluation.submitManager": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The evaluation ID */
                evaluation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResponseRequest"];
            };
        };
        responses: {
            /** @description `EvaluationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EvaluationResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "feedback.received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `FeedbackResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FeedbackResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "feedback.sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `FeedbackResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FeedbackResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "feedback.team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `FeedbackResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FeedbackResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "feedback.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackRequest"];
            };
        };
        responses: {
            /** @description `FeedbackResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FeedbackResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "feedback.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The pointwise feedback ID */
                pointwiseFeedback: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Feedback removido.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "kpi.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `KpiResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KpiResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "kpi.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreKpiRequest"];
            };
        };
        responses: {
            /** @description `KpiResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KpiResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "kpi.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The kpi ID */
                kpi: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreKpiRequest"];
            };
        };
        responses: {
            /** @description `KpiResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KpiResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "kpi.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The kpi ID */
                kpi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "KPI removido.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "kpi.indexResults": {
        parameters: {
            query?: {
                month?: number;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `KpiResultResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KpiResultResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "kpi.upsertResult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertKpiResultRequest"];
            };
        };
        responses: {
            /** @description `KpiResultResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KpiResultResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "oneOnOne.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `OneOnOneResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OneOnOneResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "oneOnOne.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOneOnOneRequest"];
            };
        };
        responses: {
            /** @description `OneOnOneResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OneOnOneResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "oneOnOne.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one on one ID */
                oneOnOne: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `OneOnOneResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OneOnOneResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "oneOnOne.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one on one ID */
                oneOnOne: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `OneOnOneResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OneOnOneResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "oneOnOne.storeTopic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one on one ID */
                oneOnOne: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        content: string;
                        addressed: boolean;
                        author_user_id: string;
                        /** Format: date-time */
                        created_at: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "oneOnOne.updateTopic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one on one ID */
                oneOnOne: string;
                /** @description The topic ID */
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        content: string;
                        addressed: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "oneOnOne.storeNote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one on one ID */
                oneOnOne: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        content: string;
                        type: string;
                        author_user_id: string;
                        /** Format: date-time */
                        created_at: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "pdi.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `PdiResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PdiResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "pdi.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePdiRequest"];
            };
        };
        responses: {
            /** @description `PdiResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PdiResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "pdi.tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The pdi ID */
                pdi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `PdiTaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PdiTaskResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "pdi.storeTask": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The pdi ID */
                pdi: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePdiTaskRequest"];
            };
        };
        responses: {
            /** @description `PdiTaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PdiTaskResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "pdi.submitTask": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The pdi ID */
                pdi: string;
                /** @description The task ID */
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PdiTaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PdiTaskResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "pdi.reviewTask": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The pdi ID */
                pdi: string;
                /** @description The task ID */
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewTaskRequest"];
            };
        };
        responses: {
            /** @description `PdiTaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PdiTaskResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "profile.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ProfileResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProfileResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "profile.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description `ProfileResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProfileResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "profile.team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ProfileResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProfileResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "sector.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SectorResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SectorResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "sector.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description `SectorResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SectorResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "sector.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The sector ID */
                sector: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description `SectorResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SectorResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "sector.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The sector ID */
                sector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Setor removido.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "smartForm.index": {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SmartFormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SmartFormResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "smartForm.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSmartFormRequest"];
            };
        };
        responses: {
            /** @description `SmartFormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SmartFormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "smartForm.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The smart form ID */
                smartForm: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SmartFormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SmartFormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "smartForm.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The smart form ID */
                smartForm: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateSmartFormRequest"];
            };
        };
        responses: {
            /** @description `SmartFormResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SmartFormResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "smartForm.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The smart form ID */
                smartForm: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Formulário removido.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "smartForm.indexResponses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The smart form ID */
                smartForm: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `SmartFormResponseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SmartFormResponseResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "smartForm.storeResponse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The smart form ID */
                smartForm: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFormResponseRequest"];
            };
        };
        responses: {
            /** @description `SmartFormResponseResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SmartFormResponseResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "smartForm.aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The smart form ID */
                smartForm: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total_responses: number;
                        averages: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "user.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "user.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "user.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "user.deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Usuário desativado.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
}
